Repository scuba-dive/shoppingmall-fe, pull requests merged in 2025-07, with the labels that each got.

#47 [Feature] 로그인 안내 모달 UI
  src/modals/SignInModal/SignInModal.jsx
  src/modals/SignInModal/SignInModal.module.css
Labels: enhancement

#48 [Feature] 장바구니 담김 안내 모달 UI
  src/modals/CartModal/CartModal.jsx
  src/modals/CartModal/CartModal.module.css
Labels: enhancement

#51 [Feature] 결제 나가기 안내 모달 UI
  src/modals/OrderCancelModal/OrderCancelModal.jsx
  src/modals/OrderCancelModal/OrderCancelModal.module.css
Labels: enhancement

#54 [Feature] 주문 내역 상세 보기 모달 UI
  src/modals/OrderInfoModal/OrderInfoModal.jsx
  src/modals/OrderInfoModal/OrderInfoModal.module.css
Labels: enhancement

#64 [Feature] Header 우측 메뉴 드롭다운화
  src/assets/user-image.png
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/components/Header/LogoutButton.module.css
Labels: refactor

#62 [Feature] 관리자 상품 수량 변경 모달 UI
  src/modals/AdminProductQuantityModal/AdminProductQuantityModal.jsx
  src/modals/AdminProductQuantityModal/AdminProductQuantityModal.module.css
Labels: enhancement

#68 [Refactor] SignIn 및 SignUp 페이지의 하위 요소 컴포넌트화 및 스키마 분리
  src/features/auth/components/SignInForm/SignInForm.jsx
  src/features/auth/components/SignInForm/SignInForm.module.css
  src/features/auth/components/SignInLinks/SignInLinks.jsx
  src/features/auth/components/SignInLinks/SignInLinks.module.css
  src/features/auth/components/SignUpForm/SignUpForm.jsx
  src/features/auth/components/SignUpForm/SignUpForm.module.css
  src/features/auth/components/SignUpLinks/SignUpLinks.jsx
  src/features/auth/components/SignUpLinks/SignUpLinks.module.css
  src/features/auth/pages/SignIn/SignIn.jsx
  src/features/auth/pages/SignIn/SignIn.module.css
  src/features/auth/pages/SignUp/SignUp.jsx
  src/features/auth/pages/SignUp/SignUp.module.css
  src/features/auth/schemas/signInSchema.js
  src/features/auth/schemas/signUpSchema.js
Labels: refactor

#90 [Feature] 이메일 중복 확인 API 연동 및 에러 메시지 처리 추가
  src/features/auth/components/SignUpForm/SignUpForm.jsx
  src/states/authStore.js
Labels: enhancement

#92 [Feature] 관리자 주문 상세 보기 API 연결 + 프로필 이미지 링크 수정
  src/components/Header/Header.jsx
  src/modals/AdminOrderInfoModal/AdminOrderInfoModal.jsx
Labels: enhancement

#97 [Refactor] Header 컴포넌트 & 관리자 주문 상세보기 모달 수정
  src/components/Header/Header.jsx
  src/components/Header/Header.module.css
  src/modals/AdminOrderInfoModal/AdminOrderInfoModal.jsx
Labels: refactor

#101 [Refactor] 회원가입 validation 로직 및 스키마 검증 추가
  src/features/auth/components/SignUpForm/SignUpForm.jsx
  src/features/auth/pages/SignUp/SignUp.jsx
  src/features/auth/schemas/signUpSchema.js
Labels: refactor

#111 [Fix] 관리자 페이지의 주문 관리 탭에서 API 호출 무한 반복 현상 개선
  src/features/admin/pages/AdminOrder/AdminOrder.jsx
  src/modals/AdminOrderInfoModal/AdminOrderInfoModal.jsx
Labels: bug

#117 [Feature] 일반 유저 주문 취소 기능 API 연결
  src/modals/AdminOrderInfoModal/AdminOrderInfoModal.jsx
  src/modals/OrderInfoModal/OrderInfoModal.jsx
Labels: enhancement

#123 [Fix] 회원가입 시 주소 입력 필드 추가
  src/features/auth/components/SignInForm/SignInForm.jsx
  src/features/auth/components/SignUpForm/SignUpForm.jsx
  src/features/auth/pages/SignUp/SignUp.jsx
  src/features/auth/schemas/signInSchema.js
  src/features/auth/schemas/signUpSchema.js
  src/states/authStore.js
Labels: enhancement, refactor

#127 [Feature] Access token 재발급 구현
  src/services/axiosInstance.js
  src/states/authStore.js
Labels: enhancement, refactor
